@startuml component_diagram_onderzoeksvraag1_ramon

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

title Container Diagram - TripTop Vakantieplan App

Person(reiziger,  "Reiziger",  "Wilt een reis boeken")
Person(reisagent, "Reisagent", "2de lijns ondersteuning")

Container_Boundary(boundary,   "TripTop Vakantieplan App - Backend") {
    Component(apicontroller,   "ApiController",   "Spring MVC REST Controller")
    Component(apiservice,      "ApiService",      "Bevat eventuele businesslogica")
    Component(apirepository,   "ApiRepository",   "Verantwoordelijk voor het ophalen van informatie uit booking.com, het cachen daarvan en het automatisch schakelen tussen de gecachde data en realtime data op basis van de beschikbaarheid")
    Component(cacherepository, "CacheRepository", "Haalt data op uit de cache")
    ComponentDb(db, "Cached Store", "Bevat gecachde data afkomstig van booking.com")
}

Rel(reiziger,  apicontroller, "Uses", "HTTPS")
Rel(reisagent, apicontroller, "Uses", "HTTPS")

Rel(apicontroller, apiservice,    "Uses")
Rel(apiservice,    apirepository, "Uses")

System_Ext(booking, "Booking.com",  "Om over overnachtingen in te plannen")

Rel(apirepository, booking,         "Uses", "JSON")
Rel(apirepository, cacherepository, "Uses")

Rel(apirepository,   db, "Reads / Writes", "JSON/SQL")
Rel(cacherepository, db, "Reads",          "JSON/SQL")

SHOW_LEGEND(true)
LAYOUT_WITH_LEGEND()

@enduml
