@startuml Betaling_Component_Diagram_Mees_Triptop

!include <C4/C4_Container>
!include <C4/C4_Component>

title "Betaling Component Diagram voor Triptop"

Container(Triptop.FrontendWebapplicatie, "Frontend Webapplicatie", "React, JavaScript", "De UI waarmee gebruikers hun reizen plannen en boeken.")

Container_Boundary(Triptop.BackendAPI, "Backend API - Betaling") {
    Component(betalingController, "BetalingController", "Java Spring", "Opent betalings API endpoints")
    Component(betalingService, "BetalingService", "Java Spring", "Handelt betalings operaties af")
    Component(betalingAdapterFactory, "BetalingAdapterFactory", "Java Spring", "Maakt betalings API's aan doormiddel van een fallback")
    Component(betalingAdapter, "BetalingAdapter", "Java Spring", "Generieke betalings API interface")
    Component(stripeBetalingAdapter, "StripeBetalingAdapter", "Java Spring", "Implementatie van de generieke betalings adapter voor Stripe")
    Component(mollieBetalingAdapter, "MollieBetalingAdapter", "Java Spring", "Implementatie van de generieke betalings adapter voor Mollie")

}

Component_Ext(stripeAPI, "StripeAPI", "?", "Voert betalings operaties uit")
Component_Ext(mollieAPI, "MollieAPI", "?", "Voert betalings operaties uit")

Rel(Triptop.FrontendWebapplicatie, betalingController, "1. Voert betaling uit", "JSON/HTTPS")
Rel(betalingController, betalingService, "2. Roept aan")
Rel_R(betalingService, betalingAdapterFactory, "3. Haal adapter op")
Rel(betalingAdapterFactory, betalingAdapter, "4. Maak adapter aan")
Rel(betalingAdapter, stripeBetalingAdapter, "5. Gebruikt")
Rel(betalingAdapter, mollieBetalingAdapter, "5. Gebruikt")

Rel(stripeBetalingAdapter, stripeAPI, "6. Voert betaling uit", "JSON/HTTPS")
Rel(mollieBetalingAdapter, mollieAPI, "6. Voert betaling uit", "JSON/HTTPS")


@enduml