@startuml
package "ese.triptop" {
    class TriptopApplication {
        - StripeTesting stripeTesting
        - WiremockTesting wiremockTesting
        - ApiArchitectureRunner apiArchitectureRunner
        + TriptopApplication(StripeTesting, WiremockTesting, ApiArchitectureRunner)
        + main(String[])
        - runStripeTest(): TriptopApplication
        - runWiremockTests(): TriptopApplication
        - runApiArchitectureDemo(): TriptopApplication
    }

    interface TravelApiServiceFacade {
        + findFlights(String, String, String, int): JsonNode
        + findHotels(double, double, String, String): JsonNode
        + findRestaurants(String): JsonNode
    }

    class TravelApiServiceFacadeImpl {
        - static String IDENTITY_BASE_URL
        - static String FLIGHT_OFFERS_URL
        - static String BOOKING_BASE_URL
        - static String TRIPADVISOR_BASE_URL
        - static String RAPIDAPI_KEY
        + findFlights(String, String, String, int): JsonNode
        + findHotels(double, double, String, String): JsonNode
        + findRestaurants(String): JsonNode
    }

    TravelApiServiceFacade <|.. TravelApiServiceFacadeImpl
}
@enduml