@startuml
package "ese.triptop" {
    
    [TriptopApplication] --> [TravelApiServiceFacadeImpl] : "Uses"

    interface TravelApiServiceFacade
    [FacadePatternRunner] --> [TravelApiServiceFacade] : "Uses"

  
    [TravelApiServiceFacadeImpl] ..|> TravelApiServiceFacade : "Implements"

    [TravelApiServiceFacadeImpl] --> [External APIs] : "Calls APIs via Unirest"
    
    package "External APIs" {
        [Flight Offers API]
        [Booking API]
        [TripAdvisor API]
    }


    [TravelApiServiceFacadeImpl] --> [Flight Offers API] 
    [TravelApiServiceFacadeImpl] --> [Booking API]
    [TravelApiServiceFacadeImpl] --> [TripAdvisor API]

}
@enduml