services:
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: pw
    ports:
      - 5433:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8070:8080